<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CHANNELS_icon-dots-vertical</name>
   <tag></tag>
   <elementGuidId>524abb81-fce2-4532-b741-54d1ee274d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-left']/div[3]/div/div/div/div/div/button/div[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-dots-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-dots-vertical</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-left&quot;)/div[3]/div[@class=&quot;scrollbar--view&quot;]/div[1]/div[@class=&quot;SidebarChannelGroup a11y__section&quot;]/div[1]/div[@class=&quot;SidebarChannelGroupHeader SidebarChannelGroupHeader--sticky&quot;]/button[@class=&quot;SidebarChannelGroupHeader_groupButton&quot;]/div[@class=&quot;MenuWrapper SidebarMenu&quot;]/button[@class=&quot;SidebarMenu_menuButton&quot;]/i[@class=&quot;icon-dots-vertical&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-left']/div[3]/div/div/div/div/div/button/div[2]/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div[2]/button/i</value>
   </webElementXpaths>
</WebElementEntity>
